version: '3.6'
services:
  postgres:
    image: postgres:10-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: shopify
      POSTGRES_PASSWORD: shopify
      POSTGRES_DB: shopify
      DB_HOST: localhost
